# Generated by Django 5.2.6 on 2025-10-30 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Call',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caller', models.CharField(blank=True, max_length=20)),
                ('receiver', models.CharField(blank=True, max_length=20)),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
                ('duration', models.CharField(blank=True, max_length=10)),
                ('active_duration', models.CharField(blank=True, max_length=10)),
                ('status', models.CharField(blank=True, max_length=20)),
                ('outgoing', models.CharField(blank=True, max_length=20)),
                ('call_id', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Extension',
            fields=[
                ('number', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('did', models.CharField(blank=True, max_length=20)),
                ('tenant', models.CharField(max_length=3)),
            ],
        ),
    ]
