# Generated by Django 5.2.6 on 2025-10-30 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20)),
                ('timezone', models.CharField(blank=True, max_length=20)),
                ('city', models.CharField(blank=True, max_length=20)),
                ('state', models.CharField(blank=True, max_length=20)),
                ('zip', models.CharField(blank=True, max_length=20)),
                ('app_id', models.CharField(blank=True, max_length=20)),
            ],
            options={
                'permissions': [('create_course', 'Can create a new course entry')],
            },
        ),
    ]
