# Generated by Django 5.2.6 on 2025-10-31 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='app_id',
        ),
        migrations.AddField(
            model_name='course',
            name='company',
            field=models.CharField(default='Digital', max_length=10),
        ),
        migrations.AddField(
            model_name='course',
            name='course_id',
            field=models.CharField(default='1', max_length=20),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='course',
            name='zip',
            field=models.CharField(default='85284', max_length=20),
        ),
    ]
