# Generated by Django 5.2.6 on 2025-10-30 17:05

import reps.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reps', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='rep',
            managers=[
                ('objects', reps.models.RepManager()),
            ],
        ),
    ]
