# Generated by Django 5.2.6 on 2025-10-31 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reps', '0002_alter_rep_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='rep',
            name='name',
            field=models.CharField(default='Test', max_length=20),
        ),
        migrations.AddField(
            model_name='rep',
            name='office',
            field=models.CharField(default='Tempe', max_length=20),
        ),
    ]
