# Generated by Django 5.2.6 on 2025-11-14 19:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_course_course_id_alter_course_name_and_more'),
        ('reps', '0004_courseassignment'),
    ]

    operations = [
        migrations.CreateModel(
            name='RepAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rep_assignments', to=settings.AUTH_USER_MODEL)),
                ('rep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manager_assignments', to='courses.course')),
            ],
        ),
    ]
