# Generated by Django 5.2.6 on 2025-11-14 19:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reps', '0005_repassignment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repassignment',
            name='rep',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manager_assignments', to=settings.AUTH_USER_MODEL),
        ),
    ]
